###
POST localhost:8000/api/autoUsate/
Accept: application/json
Content-Type: application/json

{
  "utente": 1,
  "auto": {
    "modello": "Fiat Punto XL",
    "marca": "VOLKSWAGEN",
    "altezza": 1500,
    "lunghezza": 1500,
    "larghezza": 1500,
    "peso": 25,
    "volume_bagagliaio": 12,
    "km_percorsi": 150000,
    "anno_immatricolazione": "2023-01-01",
    "targa": "AA123BB"
  }
}

###
GET http://localhost:8000/api/autoUsate/
Accept: application/json
Content-Type: application/json

###
DELETE http://localhost:8000/api/autoUsata/1/


###
DELETE http://localhost:8000/api/utente/Kenna_Lesch98@example.com/

###
GET http://localhost:8000/api/immaginiAutoNuove/1/
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8000/api/concessionari/
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8000/api/utente/Kenna_Lesch98@example.com/
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8000/api/utente/11/preventivi/
Accept: application/json
Content-Type: application/json

{
  "preventivo": {
    "utente": 11,
    "concessionario": 1,
    "modello": 1,
    "prezzo": 20000
  },
  "optional": [
    3,
    13,
    48
  ],
  "detrazione": 1
}


###
GET http://localhost:8000/api/utente/1/preventivi/
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8000/api/modelli/
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8000/api/optionals/
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8000/api/utente/11/preventivo/64/conferma/
Accept: application/json
Content-Type: application/json

{
  "acconto": 1500
}