# Generated by Django 5.0.6 on 2024-05-08 12:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Impiegato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("nome", models.CharField(max_length=20)),
                ("cognome", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ModelloAuto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, unique=True)),
                (
                    "marca",
                    models.CharField(
                        choices=[
                            ("Nissan", "Nissan"),
                            ("Mazda", "Mazda"),
                            ("Volkswagen", "Volkswagen"),
                            ("Ford", "Ford"),
                            ("Honda", "Honda"),
                            ("Audi", "Audi"),
                            ("BMW", "Bmw"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prezzo_base", models.IntegerField()),
                ("altezza", models.IntegerField()),
                ("lunghezza", models.IntegerField()),
                ("larghezza", models.IntegerField()),
                ("peso", models.IntegerField()),
                ("volume_bagagliaio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Optional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("colore", "Colore"),
                            ("cambio", "Cambio"),
                            ("motorizzazione", "Motorizzazione"),
                            ("dimensione cerchi", "Dim Cerchi"),
                            ("stereo", "Stereo"),
                            ("fanali", "Fanali"),
                            ("finestrini", "Finestrini"),
                            ("scarico", "Scarico"),
                            ("sospensioni", "Sospensioni"),
                            ("sedili", "Sedili"),
                            ("infotainment", "Infotainment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descrizione", models.CharField(max_length=30)),
                ("prezzo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, unique=True)),
                ("via", models.CharField(max_length=20)),
                ("civico", models.CharField(max_length=5)),
                ("citta", models.CharField(max_length=20)),
                ("cap", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Utente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("nome", models.CharField(max_length=20)),
                ("cognome", models.CharField(max_length=20)),
                ("numero_carta", models.CharField(max_length=20)),
                ("data_scadenza", models.DateField()),
                ("cvc", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Configurazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modello",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.modelloauto",
                    ),
                ),
                (
                    "cambio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cambio",
                        to="Backend_IngSoft.optional",
                    ),
                ),
                (
                    "colore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colore",
                        to="Backend_IngSoft.optional",
                    ),
                ),
                (
                    "dim_cerchi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dim_cer",
                        to="Backend_IngSoft.optional",
                    ),
                ),
                (
                    "fanali",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fanali",
                        to="Backend_IngSoft.optional",
                    ),
                ),
                (
                    "finestrini",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finestrini",
                        to="Backend_IngSoft.optional",
                    ),
                ),
                (
                    "infotainment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infotainment",
                        to="Backend_IngSoft.optional",
                    ),
                ),
                (
                    "motorizzazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motorizzazione",
                        to="Backend_IngSoft.optional",
                    ),
                ),
                (
                    "scarico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scarico",
                        to="Backend_IngSoft.optional",
                    ),
                ),
                (
                    "sedili",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sedili",
                        to="Backend_IngSoft.optional",
                    ),
                ),
                (
                    "sospensioni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sospensioni",
                        to="Backend_IngSoft.optional",
                    ),
                ),
                (
                    "stereo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stereo",
                        to="Backend_IngSoft.optional",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mese",
                    models.CharField(
                        choices=[
                            ("gennaio", "Gennaio"),
                            ("febbraio", "Febbraio"),
                            ("marzo", "Marzo"),
                            ("aprile", "Aprile"),
                            ("maggio", "Maggio"),
                            ("giugno", "Giugno"),
                            ("luglio", "Luglio"),
                            ("agosto", "Agosto"),
                            ("settembre", "Settembre"),
                            ("ottobre", "Ottobre"),
                            ("novembre", "Novembre"),
                            ("dicembre", "Dicembre"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "anno",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(9999)]
                    ),
                ),
            ],
            options={
                "unique_together": {("mese", "anno")},
            },
        ),
        migrations.CreateModel(
            name="Preventivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emissione", models.DateField()),
                ("prezzo", models.IntegerField()),
                (
                    "configurazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.configurazione",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.sede",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.utente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentuale_sconto",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "modello",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.modelloauto",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.periodo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutoUsata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modello", models.CharField(max_length=20)),
                ("marca", models.CharField(max_length=20)),
                ("prezzo", models.IntegerField(default=0)),
                ("km_percorsi", models.IntegerField()),
                ("anno_immatricolazione", models.DateField()),
                ("altezza", models.IntegerField()),
                ("lunghezza", models.IntegerField()),
                ("larghezza", models.IntegerField()),
                ("peso", models.IntegerField()),
                ("volume_bagagliaio", models.IntegerField()),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.utente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Acquisto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_fattura", models.CharField(max_length=10, unique=True)),
                ("acconto", models.IntegerField()),
                ("data_ritiro", models.DateField()),
                (
                    "preventivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.preventivo",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.utente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImmaginiAutoUsate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                (
                    "auto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.autousata",
                    ),
                ),
            ],
            options={
                "unique_together": {("path", "auto")},
            },
        ),
        migrations.CreateModel(
            name="Gestione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_usata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.autousata",
                    ),
                ),
                (
                    "impiegato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.impiegato",
                    ),
                ),
            ],
            options={
                "unique_together": {("impiegato", "auto_usata")},
            },
        ),
        migrations.CreateModel(
            name="ImmaginiAutoNuove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                (
                    "auto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.modelloauto",
                    ),
                ),
            ],
            options={
                "unique_together": {("path", "auto")},
            },
        ),
        migrations.CreateModel(
            name="Possiede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modello",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.modelloauto",
                    ),
                ),
                (
                    "optional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.optional",
                    ),
                ),
            ],
            options={
                "unique_together": {("modello", "optional")},
            },
        ),
        migrations.CreateModel(
            name="Detrazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_usata",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.autousata",
                    ),
                ),
                (
                    "preventivo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.preventivo",
                    ),
                ),
            ],
            options={
                "unique_together": {("preventivo", "auto_usata")},
            },
        ),
        migrations.CreateModel(
            name="Ritiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preventivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.preventivo",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.sede",
                    ),
                ),
            ],
            options={
                "unique_together": {("preventivo", "sede")},
            },
        ),
    ]
