# Generated by Django 5.0.6 on 2024-05-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Backend_IngSoft", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="configurazione",
            unique_together={("preventivo", "optional")},
        ),
    ]
