# Generated by Django 5.0.6 on 2024-05-08 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend_IngSoft", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodo",
            name="anno",
            field=models.IntegerField(
                choices=[
                    (2000, 2000),
                    (2001, 2001),
                    (2002, 2002),
                    (2003, 2003),
                    (2004, 2004),
                    (2005, 2005),
                    (2006, 2006),
                    (2007, 2007),
                    (2008, 2008),
                    (2009, 2009),
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                    (2024, 2024),
                ],
                default=2024,
                validators=[django.core.validators.MaxValueValidator(9999)],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sconto",
            unique_together={("periodo", "modello")},
        ),
        migrations.AlterModelTable(
            name="acquisto",
            table="acquisto",
        ),
        migrations.AlterModelTable(
            name="autousata",
            table="auto_usata",
        ),
        migrations.AlterModelTable(
            name="configurazione",
            table="configurazione",
        ),
        migrations.AlterModelTable(
            name="detrazione",
            table="detrazione",
        ),
        migrations.AlterModelTable(
            name="gestione",
            table="gestione",
        ),
        migrations.AlterModelTable(
            name="immaginiautonuove",
            table="immagini_auto_nuove",
        ),
        migrations.AlterModelTable(
            name="immaginiautousate",
            table="immagini_auto_usate",
        ),
        migrations.AlterModelTable(
            name="impiegato",
            table="impiegato",
        ),
        migrations.AlterModelTable(
            name="modelloauto",
            table="modello_auto",
        ),
        migrations.AlterModelTable(
            name="optional",
            table="optional",
        ),
        migrations.AlterModelTable(
            name="periodo",
            table="periodo",
        ),
        migrations.AlterModelTable(
            name="possiede",
            table="possiede_optional",
        ),
        migrations.AlterModelTable(
            name="preventivo",
            table="preventivo",
        ),
        migrations.AlterModelTable(
            name="ritiro",
            table="sede_ritiro",
        ),
        migrations.AlterModelTable(
            name="sconto",
            table="sconto",
        ),
        migrations.AlterModelTable(
            name="sede",
            table="sede_concessionario",
        ),
        migrations.AlterModelTable(
            name="utente",
            table="utente",
        ),
    ]
