# Generated by Django 5.0.1 on 2024-05-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="immaginiautonuove",
            options={"verbose_name_plural": "Immagini Auto Nuove"},
        ),
        migrations.AlterField(
            model_name="immaginiautonuove",
            name="img",
            field=models.ImageField(default=None, upload_to="imageAutoNuove"),
        ),
    ]
