# Generated by Django 5.0.6 on 2024-06-11 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="preventivo",
            unique_together=set(),
        ),
    ]
