# Generated by Django 5.0.6 on 2024-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utente",
            name="indirizzo",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="utente",
            name="numero_telefono",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
