# Generated by Django 5.0.6 on 2024-06-02 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0002_utente_indirizzo_utente_numero_telefono"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modelloauto",
            old_name="nome",
            new_name="modello",
        ),
        migrations.RemoveField(
            model_name="autousata",
            name="utente",
        ),
        migrations.AlterField(
            model_name="autousata",
            name="modello",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="PreventivoUsato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.autousata",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Backend_IngSoft.utente",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Preventivi Auto Usate",
                "unique_together": {("utente", "auto")},
            },
        ),
    ]
