# Generated by Django 5.0.6 on 2024-06-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0002_alter_preventivo_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preventivo",
            name="data_emissione",
            field=models.DateField(null=True),
        ),
    ]
