# Generated by Django 5.0.6 on 2024-06-23 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0002_autousata_venduta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodo",
            name="anno",
            field=models.PositiveIntegerField(
                choices=[
                    (2024, 2024),
                    (2025, 2025),
                    (2026, 2026),
                    (2027, 2027),
                    (2028, 2028),
                ],
                default=2024,
                validators=[django.core.validators.MaxValueValidator(9999)],
            ),
        ),
    ]
