# Generated by Django 5.0.6 on 2024-05-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0002_alter_immaginiautonuove_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immaginiautonuove",
            name="img",
            field=models.ImageField(default=None, upload_to="image"),
        ),
    ]
