# Generated by Django 5.0.6 on 2024-05-16 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend_IngSoft", "0002_alter_configurazione_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autousata",
            options={"verbose_name_plural": "Auto Usate"},
        ),
        migrations.AlterModelOptions(
            name="modelloauto",
            options={"verbose_name_plural": "Modelli Auto"},
        ),
        migrations.AlterModelOptions(
            name="optional",
            options={"verbose_name_plural": "Optional"},
        ),
        migrations.AlterModelOptions(
            name="ritiro",
            options={"verbose_name_plural": "Ritiro Auto"},
        ),
        migrations.AlterModelOptions(
            name="sconto",
            options={"verbose_name_plural": "Sconti"},
        ),
        migrations.AlterModelOptions(
            name="sede",
            options={"verbose_name_plural": "Sedi"},
        ),
        migrations.AlterModelOptions(
            name="utente",
            options={"verbose_name_plural": "Utenti"},
        ),
        migrations.AlterField(
            model_name="autousata",
            name="prezzo",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="optional",
            unique_together={("nome", "descrizione")},
        ),
        migrations.AlterUniqueTogether(
            name="sconto",
            unique_together={("periodo", "modello")},
        ),
    ]
