# Generated by Django 5.0.6 on 2024-05-29 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0003_alter_immaginiautonuove_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="immaginiautonuove",
            old_name="img",
            new_name="image",
        ),
        migrations.AlterUniqueTogether(
            name="immaginiautonuove",
            unique_together={("image", "auto")},
        ),
    ]
