# Generated by Django 5.0.6 on 2024-06-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0003_alter_preventivo_data_emissione"),
    ]

    operations = [
        migrations.AddField(
            model_name="preventivo",
            name="valid",
            field=models.BooleanField(default=True),
        ),
    ]
