# Generated by Django 5.0.6 on 2024-06-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0003_rename_nome_modelloauto_modello_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="configurazione",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="configurazione",
            name="preventivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Backend_IngSoft.preventivo",
            ),
        ),
        migrations.RemoveField(
            model_name="configurazione",
            name="optional",
        ),
        migrations.AddField(
            model_name="configurazione",
            name="optional",
            field=models.ManyToManyField(to="Backend_IngSoft.optional"),
        ),
    ]
