# Generated by Django 5.0.6 on 2024-06-14 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend_IngSoft", "0004_preventivo_valid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="immaginiautonuove",
            name="phash",
        ),
        migrations.RemoveField(
            model_name="immaginiautousate",
            name="phash",
        ),
        migrations.AlterField(
            model_name="acquisto",
            name="acconto",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="autousata",
            name="altezza",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="autousata",
            name="km_percorsi",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="autousata",
            name="larghezza",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="autousata",
            name="lunghezza",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="autousata",
            name="peso",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="autousata",
            name="prezzo",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="autousata",
            name="volume_bagagliaio",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="modelloauto",
            name="altezza",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="modelloauto",
            name="larghezza",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="modelloauto",
            name="lunghezza",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="modelloauto",
            name="peso",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="modelloauto",
            name="prezzo_base",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="modelloauto",
            name="volume_bagagliaio",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="optional",
            name="prezzo",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="periodo",
            name="anno",
            field=models.PositiveIntegerField(
                choices=[
                    (2000, 2000),
                    (2001, 2001),
                    (2002, 2002),
                    (2003, 2003),
                    (2004, 2004),
                    (2005, 2005),
                    (2006, 2006),
                    (2007, 2007),
                    (2008, 2008),
                    (2009, 2009),
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                    (2024, 2024),
                ],
                default=2024,
                validators=[django.core.validators.MaxValueValidator(9999)],
            ),
        ),
        migrations.AlterField(
            model_name="preventivo",
            name="prezzo",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="sconto",
            name="percentuale_sconto",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="utente",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
