# Generated by Django 5.0.6 on 2024-06-02 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0004_alter_configurazione_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="preventivo",
            unique_together={("id", "utente", "modello", "data_emissione")},
        ),
    ]
