# Generated by Django 5.0.6 on 2024-06-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0005_remove_immaginiautonuove_phash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autousata",
            name="marca",
            field=models.CharField(
                choices=[
                    ("NISSAN", "Nissan"),
                    ("MAZDA", "Mazda"),
                    ("VOLKSWAGEN", "Volkswagen"),
                    ("FORD", "Ford"),
                    ("HONDA", "Honda"),
                    ("AUDI", "Audi"),
                    ("BMW", "Bmw"),
                ],
                max_length=20,
            ),
        ),
    ]
