# Generated by Django 5.0.6 on 2024-06-02 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0005_alter_preventivo_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="preventivo",
            unique_together={("utente", "modello", "data_emissione")},
        ),
    ]
