# Generated by Django 5.0.6 on 2024-06-03 05:54

import Backend_IngSoft.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend_IngSoft", "0006_alter_preventivo_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="autousata",
            name="targa",
            field=models.CharField(
                default="AA000AA",
                max_length=7,
                validators=[Backend_IngSoft.models.validate_targa],
            ),
        ),
        migrations.AlterField(
            model_name="autousata",
            name="anno_immatricolazione",
            field=models.DateField(
                validators=[Backend_IngSoft.models.validate_not_future_date]
            ),
        ),
        migrations.AlterField(
            model_name="autousata",
            name="km_percorsi",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
